### ISSUE TITLE
Ошибка - сканирование по ПКМ

### ISSUE THREAD

**Issue by EKashpersky** [EKashpersky/galamakers#16]
Submitter: Артем Н
После сканирования чужого корабля нажатие ПКМ по кораблю героя вызывает окно сканирования с фитом последнего просканированного. Повторное нажатие по кораблю героя вызывает адекватное обновление.

**Comment by EKashpersky** [comment]
@doctor911 тут бага, чекни.

**Comment by doctor911** [comment]
Fixed
