### ISSUE TITLE
Ошибка - Артефакт Полароид

### ISSUE THREAD

**Issue by EKashpersky** [EKashpersky/galamakers#19]
Submitter: Артем Н
Email: Teemon-99@yandex.ru
https://imgur.com/a/oUsK9eL - ГЗП героя 34%, артефакт должен давать +10% к силовому полю, но счетчик в углу показывает всё те же 34%. Снятие-надевание не помогает, логом боя проверить тяжело, т.к. у всего оружия есть разброс, но всё же, кажется, он не работает. По крайней мере - баг с отображением счетчика есть точно.

**Comment by EKashpersky** [comment]
@doctor911 можешь проверить?

**Comment by doctor911** [comment]
Исправлено.
