### ISSUE TITLE
Ошибка - Артефакт Стальной рой

### ISSUE THREAD

**Issue by Teemonus** [EKashpersky/galamakers#24]
Ошибка схожа с багом Полароида - при надевании арта "Стальной рой" в счетчике статов не прибавляется +5 брони (как было 13, так и осталось), однако в бою всё считается правильно (3 скриншот - сначала удар лазером 16 урона по цели без ГЗП и роя, потом с Роем*.)

https://imgur.com/2aVNh0U
https://imgur.com/VnccICU
https://imgur.com/nrdha0j

**Comment by EKashpersky** [comment]
@doctor911

**Comment by doctor911** [comment]
Fixed
