### ISSUE TITLE
Ошибка - формула расчета урона!

### ISSUE THREAD

**Issue by Teemonus** [EKashpersky/galamakers#25]
Допущена ошибка в формуле расчета урона.
Сымитировал ситуацию.
на меня нападают легковооруженные противники, с лазерами. Урон лазеров 16-18.
на мне же - ГЗП 34% + арт Полароид (+10%) и корпус с 13 брони.
По идее...
16 урона, затем... 
Урон режется ГЗП - мощь ГЗП 44%, значит остается 56% урона -> 16*0.56=8.96 (округлим до 9), затем...
Урон режется БРОНЕЙ - 9-13=-4 (меньше нуля, урон не прошел).

Потом тесты - я снял ГЗП и меня били лазером 16-18. Получалось 3-4, иногда 5. Т.к. 16-18 урона - броня = 16-13=3, 18-13=5... ну примерно всё верно. А вот с активным ГЗП на 34%+арт (где в теории выше меня не должны были вообще пробивать) я получал 2 урона.
То есть ГЗП режет уже ПРОШЕДШИЙ урон по герою. 3-5 * 0.56= 1.68-2.8

12-13 марта - без ГЗП, 14-15 марта - с ГЗП и артом.

https://imgur.com/6bqngWx

**Comment by EKashpersky** [comment]
@doctor911 panic over here!

**Comment by doctor911** [comment]
Fixed
